# Data Science Projects - Movie Analytics

Author : Albert Christian Yang
<br>
Kaggle Link : https://www.kaggle.com/datasets/rounakbanik/the-movies-dataset/data

### Library
---

In [51]:
import numpy as np # Mathematics Operation
import pandas as pd # Data Analysis
import seaborn as sns # Data Visualisation
import matplotlib.pyplot as plt # Data Visualisation

---

### Import Data

In [52]:
movies_data = pd.read_csv('./movies_metadata.csv/movies_metadata.csv')
ratings_data = pd.read_csv('./ratings.csv/ratings.csv')

C:\Users\Albert\AppData\Local\Temp\ipykernel_17312\1919781629.py:1: DtypeWarning: Columns (10: popularity) have mixed types. Specify dtype option on import or set low_memory=False.
  movies_data = pd.read_csv('./movies_metadata.csv/movies_metadata.csv')

---

### Exploratory Data Analysis

Dataset's Row and Collumn

In [66]:
print(f"Number of Rows : " , movies_data.shape[0])
print(f"Number of Collumns : " , movies_data.shape[1])

Number of Rows :  45466
Number of Collumns :  24

The First 5 Data of Movies Data

In [53]:
movies_data.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

The Last 5 Data of Movies Data

In [54]:
movies_data.tail()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
45461,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,NaN,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0
45462,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3.0
45463,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0
45464,False,NaN,0,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0
45465,False,NaN,0,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0

The Random 5 Data of Movies Data

In [55]:
movies_data.sample(5)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
32102,False,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",NaN,61312,tt1740712,en,"Video Nasties: Moral Panic, Censorship & Video...",A documentary analyzing the furore which so-ca...,...,2010-08-30,0.0,72.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,72 films that changed Britain forever.,"Video Nasties: Moral Panic, Censorship & Video...",False,7.2,9.0
12779,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 27, 'nam...",NaN,13022,tt0479528,en,Rogue,From the director of Wolf Creek comes this ter...,...,2007-11-08,0.0,99.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,How Fast Can You Swim?,Rogue,False,6.2,151.0
6336,False,"{'id': 57129, 'name': 'Rugrats Collection', 'p...",0,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",NaN,20694,tt0337711,en,Rugrats Go Wild,Rugrats Go Wild is a 2003 crossover animated f...,...,2003-06-13,0.0,84.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Family Vacation Goes Overboard,Rugrats Go Wild,False,5.6,62.0
32812,False,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",NaN,328132,tt2936552,en,Earth's Golden Playground,Since the first Gold Rush in the late 1890s th...,...,2015-03-13,0.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Earth's Golden Playground,False,0.0,0.0
3154,False,NaN,1000000,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",NaN,12143,tt0103759,en,Bad Lieutenant,"While investigating a young nun's rape, a corr...",...,1992-09-16,2019469.0,96.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Gambler. Thief. Junkie. Killer. Cop.,Bad Lieutenant,False,6.9,162.0

Movies Data Info

In [56]:
movies_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  str
 1   belongs_to_collection  4494 non-null   str
 2   budget                 45466 non-null  str
 3   genres                 45466 non-null  str
 4   homepage               7782 non-null   str
 5   id                     45466 non-null  str
 6   imdb_id                45449 non-null  str
 7   original_language      45455 non-null  str
 8   original_title         45466 non-null  str
 9   overview               44512 non-null  str
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  str
 12  production_companies   45463 non-null  str
 13  production_countries   45463 non-null  str
 14  release_date           45379 non-null  str
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  str
 18  status                 45379 non-null  str
 19  tagline                20412 non-null  str
 20  title                  45460 non-null  str
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(2), str(18)
memory usage: 8.3+ MB

Statistical Summary Analyst of Movies Data

In [57]:
movies_data.describe()

            revenue       runtime  vote_average    vote_count
count  4.546000e+04  45203.000000  45460.000000  45460.000000
mean   1.120935e+07     94.128199      5.618207    109.897338
std    6.433225e+07     38.407810      1.924216    491.310374
min    0.000000e+00      0.000000      0.000000      0.000000
25%    0.000000e+00     85.000000      5.000000      3.000000
50%    0.000000e+00     95.000000      6.000000     10.000000
75%    0.000000e+00    107.000000      6.800000     34.000000
max    2.787965e+09   1256.000000     10.000000  14075.000000

In [58]:
ratings_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 26024289 entries, 0 to 26024288
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   userId     int64
 1   movieId    int64
 2   rating     float64
 3   timestamp  int64
dtypes: float64(1), int64(3)
memory usage: 794.2 MB

In [59]:
movies_data.loc["Toy Story"]

KeyError: 'Toy Story'

In [ ]:
movies_data = movies_data.reset_index()

In [ ]:
movies_data.loc[:, ["original_title", "budget", "original_language"]]

                    original_title    budget original_language
0                        Toy Story  30000000                en
1                          Jumanji  65000000                en
2                 Grumpier Old Men         0                en
3                Waiting to Exhale  16000000                en
4      Father of the Bride Part II         0                en
...                            ...       ...               ...
45461                      رگ خواب         0                fa
45462          Siglo ng Pagluluwal         0                tl
45463                     Betrayal         0                en
45464          Satana likuyushchiy         0                en
45465                     Queerama         0                en

[45466 rows x 3 columns]

In [ ]:
movies_data.columns

Index(['original_title', 'adult', 'belongs_to_collection', 'budget', 'genres',
       'homepage', 'id', 'imdb_id', 'original_language', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='str')